apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k3s-agent.yaml
  - k3s-server.yaml

bases:
  - github.com/rancher/system-upgrade-controller

generatorOptions:
  disableNameSuffixHash: true
