kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: troy.cns.me
            - name: NFS_PATH
              value: /volume4/cluster-store
      volumes:
        - name: nfs-client-root
          nfs: 
            server: troy.cns.me
            path: /volume4/cluster-store