nameSuffix: -usa
# secretGenerator:
#   - name: zwave2mqtt
#     files:
#       - settings.json
  # - name: auth
  #   files:
  #     - auth

patches:
  - path: pvc.yaml
  - path: deployment.yaml
  - path: service.yaml

commonLabels:
  zwave: usa

resources:
  - ../zwavejs-base
  - ingress.yaml

generatorOptions:
  disableNameSuffixHash: true
