apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- envs:
  - .env
  name: paparazzogo

# generatorOptions:
#   disableNameSuffixHash: true

  # - external_back
resources:
- external_driveway
- external_front
- external_down
- external_garden
- external_porch
- namespace.yaml

namespace: paparazzogo
