apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: p-cns-me-wildcard-cert
spec:
  secretName: p-cns-me-wildcard-cert
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
  - '*.p.cns.me'