apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: octoprint-https
spec:
  secretName: octoprint-https
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - 'octoprint.p.cns.me' 