apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scrypted-https
spec:
  secretName: scrypted-https
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - 'scrypted.p.cns.me'