nameSuffix: -eu
resources:
  - ../zwavejs-base
  - ingress.yaml

# secretGenerator:
#   - name: zwave2mqtt
#     files:
#       - settings.json
  # - name: auth
  #   files:
  #     - auth

commonLabels:
  zwave: eu

patches:
  - path: pvc.yaml
  - path: deployment.yaml
  - path: service.yaml


generatorOptions:
  disableNameSuffixHash: true
