apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sm2uploader-https
spec:
  secretName: sm2uploader-https
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - 'sm2uploader.p.cns.me'