apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hp-m575m
spec:
  secretName: hp-m575m-https
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "hp-m575m.cns.me"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hp-m575m
spec:
  schedule: "35 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          dnsPolicy: "None"
          dnsConfig:
            nameservers:
              - 192.168.0.1
          containers:
            - name: hp-m575m
              image: wbitt/network-multitool:latest
              command: ["sh", "-c"]
              args:
              - |
                  openssl pkcs12 -export -out certificate.pfx -password pass:password -inkey /cert/tls.key -in /cert/tls.crt 
                  curl 'https://hp-m575m.cns.me/hp/device/SignIn/Index' -v \
                    -c ./cookies.txt \
                    --form agentIdSelect=hp_EmbeddedPin_v1 \
                    --form PinDropDown=AdminItem \
                    --form PasswordTextBox=${HP_PASSWORD} \
                    --form signInOk=Sign+In \
                    --insecure
                  curl -v -b ./cookies.txt --insecure \
                    --form .Import_FileName_handle=@certificate.pfx \
                    --form Finish=Finish \
                    --form CSRFToken= \
                    --form Hide=Hide \
                    --form password=password \
                    https://hp-m575m.cns.me/websecurity/cert_import.htm/config
              envFrom:
                - secretRef:
                    name: secrets
              volumeMounts:
                - name: cert
                  mountPath: /cert
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: cert
              secret:
                secretName: hp-m575m-https
