apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - hp-m575m.cns.me.yaml

configMapGenerator:
  - name: hp-m575m-robot
    files:
      - HPRenewal.robot

secretGenerator:
  - name: secrets
    env: env.txt

namespace: devices-tls