apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
  - github.com/metallb/metallb//manifests?ref=v0.13.9

configMapGenerator:
- name: config
  files:
    - config=config.yaml

secretGenerator:
- name: memberlist
  files:
    - secretkey

generatorOptions:
 disableNameSuffixHash: true