apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
- github.com/metallb/metallb/config/native?ref=v0.13.9
- ipaddresspool.yaml
- l2advertisement.yaml

# configMapGenerator:
# - name: config
#   files:
#     - config=config.yaml

secretGenerator:
- name: memberlist
  files:
    - secretkey

generatorOptions:
 disableNameSuffixHash: true