apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frigate-https
spec:
  secretName: frigate-https
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - 'frigate.p.cns.me'