apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddns
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 180
      template:
        spec:
          containers:
            - name: ddns
              image: curlimages/curl
              securityContext:
                runAsUser: 1000
                runAsGroup: 3000
              envFrom:
                - secretRef:
                    name: secret
              command: ["/bin/sh"]
              args:
                [
                  "-c",
                  'curl -s -X PUT https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD} -H "Authorization: Bearer ${API_KEY}" -H Content-Type:application/json --data "{\"type\":\"A\",\"name\":\"${ADDRESS}\",\"content\":\"$(curl -s https://api.ipify.org)\",\"ttl\":60,\"proxied\":true}"'
                ]
          restartPolicy: OnFailure
