apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
        - name: external-dns
          args:
            - --source=ingress
            - --domain-filter=cns.me
            - --provider=cloudflare
          envFrom:
            - secretRef:
                name: cloudflare