apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/kubernetes-sigs/external-dns/kustomize?ref=v0.16.1
  - namespace.yaml

secretGenerator:
  - name: cloudflare
    env: .env
    type: Opaque

patches:
  - path: deployment.yaml

namespace: external-dns